[build]
  command = "npm run build"
  publish = "build"
  functions = "functions"  # Points to your functions directory

[functions]
  node_bundler = "esbuild"

  [functions.timeout]
  default = 10  # Seconds (max for free tier)
  max = 10

# Optional: For Single Page Apps (React)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200